# Build `qt-dummy`

The process for creating the conda-smithy `qt-dummy-feedstock`.

Starting from link:https://github.com/phreed/my-conda-pkg-feedstock[the sample].
There are several tutorials and `conda-smithy` is moving quickly.

The main file is `recipe/meta.yaml`.
[source,yaml]
----
include::meta.yaml[]
----

## Create Repository

A fresh git repository `qt-dummy-feedstock` can be generated.
The only required content is `recipe/meta.yaml`.

[source,cmd]
----
mamba smithy init --feedstock-directory ../qt-dummy-feedstock2 ./recipe
----

## GitHub Registration

Configure the upload channels.
[source,yaml]
----
include::../conda-forge.yml[]
----

The feedstock needs to be registered with github.
The github personal access token must be present in the `~/.conda-smithy/github.token` file.
You can generate a personal access token at https://github.com/settings/tokens.

[source,cmd]
----
mamba smithy register-github --user phreed .
----

## CI Registration

[source,cmd]
----
mamba smithy register-ci --feedstock_directory . --user phreed --without-travis --without-circle --without-drone --without-azure --without-appveyor
----

[source,cmd]
----
mamba smithy update-anaconda-token --feedstock_directory . --user phreed --without-travis --without-circle --without-drone --without-azure --without-appveyor
----

Now build the scripts needed by the specified tooling.

[source,cmd]
----
mamba smithy regenerate --feedstock_directory .
----
Finally, push the configured feedstock to github for building and deployment.

[source,cmd]
----
cd .\qt-dummy-feedstock
git commit -m ""
git push upstream main
----

That seems to do the trick.
