# This feedstock wraps existing binary distributions.
{% set name = "qt-dummy" %}
{% set version = "5.2.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  noarch: generic
  number: 0

requirements:
  build:
    - numpy {{ numpy }}
  host: []
  run: []

test:
  requires:
  files:
#    - test/hello.pro
#    - test/main-qtwebengine.cpp
#    - test/main.cpp
#    - test/main.qml
#    - test/qml.qrc
#    - test/qrc_qml.cpp
#    - test/qtwebengine.pro
  commands:
    - if not exist %LIBRARY_BIN%\\Qt5WebEngine.dll exit 1                  # [win]
    - if not exist %LIBRARY_PREFIX%\plugins\sqldrivers\qsqlite.dll exit 1  # [win]
    - test -f $PREFIX/lib/libQt5WebEngine${SHLIB_EXT}                      # [unix]
    - test -f $PREFIX/plugins/sqldrivers/libqsqlite${SHLIB_EXT}            # [unix]

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
    This module provides a dummy installer for Qt.
    It does not install any Qt package.
    It configures the specified Conda environment to use the installed Qt.
    It expects the appropriate Qt to have been previously acquired.
  doc_url: https://www.qt.io/blog/2014/02/05/qt-5-2-1-released
  dev_url: https://github.com/qtproject

extra:
  recipe-maintainers:
    - 'phreed'
