
github:
  user_or_org: phreed
#  branch_name: v5.2.1
#  tooling_branch_name: main

channels:
  targets:
    - [mesomorph,main]
provider:
  osx: github_actions
  linux: github_actions
  win: github_actions
github_actions:
  upload_packages: True
upload_on_branch: v5.2.1

